[font]
size = 17

[font.normal]
family = "IoskeleyMonoTerm Nerd Font Mono"
style = "Regular"

[font.bold]
family = "IoskeleyMonoTerm Nerd Font Mono"
style = "Bold"

[font.italic]
family = "IoskeleyMonoTerm Nerd Font Mono"
style = "Italic"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[terminal.shell]
program = "tmux"
