#!/bin/bash

set -euo pipefail

SOURCE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

if command -v chezmoi >/dev/null 2>&1 && chezmoi --version >/dev/null 2>&1; then
    chezmoi init --apply --source "$SOURCE_DIR"
    exit 0
fi

if command -v mise >/dev/null; then
    mise exec chezmoi@latest -- chezmoi init --apply --source "$SOURCE_DIR"
    exit 0
fi

sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply --source "$SOURCE_DIR"
exit 0
