[tools]
node = "24"
bat = "latest"
tmux = "latest"
chezmoi = "latest"
vim = "latest"
starship = "latest"
gh = "latest"
neovim = "latest"
yazi = "latest"
fd = "latest"
fzf = "latest"
lazygit = "latest"
ripgrep = "latest"
jq = "latest"
glab = "latest"
kubectl = "latest"
helm = "latest"
flux2 = "latest"
