"$schema" = 'https://starship.rs/config-schema.json'

format = """
($username$hostname${custom.remote_host} )\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[username]
format = '[$user]($style)'
style_user = "#928374"
style_root = "#ea6962"
detect_env_vars = ["REMOTE_CONTAINERS"]

[hostname]
format = '[@$hostname]($style)'
style = "#928374"

[custom.remote_host]
command = 'printf "%s" "${DEVPOD_WORKSPACE_ID:-$(hostname -s)}"'
when = 'test -n "$REMOTE_CONTAINERS"'
format = '[@$output]($style)'
style = "#928374"
os = "linux"

[directory]
style = "#d8a657"

[character]
success_symbol = "[❯](#e78a4e)"
error_symbol = "[❯](#ea6962)"
vimcmd_symbol = "[❮](#d3869b)"

[git_branch]
format = "[$branch]($style)"
style = "#d8a657"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#d3869b) ($ahead_behind$stashed)]($style)"
style = "#d3869b"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#928374"

[cmd_duration]
format = "[$duration]($style) "
style = "#e78a4e"

[python]
format = "[$virtualenv]($style) "
style = "#928374"
detect_extensions = []
detect_files = []
